### ISSUE TITLE
add per-file domain_id mapping to task matrix

### ISSUE THREAD

**Issue by croeder** [cladteam/CCDA_OMOP_by_Python#51] opened 2024-08-12 02:50 UTC
CCDA-tools/create_map_to_standard.py creates a map from (oid, concept_code) to concept_id, but includes section.

If we apply the mapping to the files individually, we can see how the domain_id routing breaks out per file and fill in that data to the task matrix, and we can set epectations for the output mapping.

**Comment by chrisroederucdenver** [comment] 2024-09-04 22:49
Duplicate of #82

**Closed by chrisroederucdenver** 2024-09-04 22:49 UTC
Labels: analysis, DQ, Uber Coverage
